[package]
name = "title_ansi_terminal"
version = "0.1.0"
authors = ["Stephen Sherratt <stephen@sherra.tt>"]

[dependencies]
prototty_ansi_terminal = { path = "../../../ansi-terminal" }
prototty_title = { path = "../prototty" }
