[package]
name = "glutin_title"
version = "0.1.0"
authors = ["Stephen Sherratt <sfsherratt@gmail.com>"]

[dependencies]
prototty = { path = "../../../prototty", version = "0.19" }
prototty_glutin = { path = "../../../glutin", version = "0.19" }
prototty_title = { path = "../prototty" }
