[package]
name = "glutin_title"
version = "0.1.0"
authors = ["Stephen Sherratt <stephen@sherra.tt>"]

[dependencies]
prototty_glutin = { path = "../../../glutin" }
prototty_title = { path = "../prototty" }
