[package]
name = "tetris_ansi_terminal"
version = "0.1.0"
authors = ["Stephen Sherratt <stephen@sherra.tt>"]
edition = "2018"

[dependencies]
tetris_prototty = { path = "../prototty" }
prototty_ansi_terminal = { path = "../../../ansi-terminal" }
rand = "0.7"
