[package]
name = "pager_web"
version = "0.1.0"
authors = ["Stephen Sherratt <stephen@sherra.tt>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
prototty_web = { path = "../../../web" }
pager_prototty = { path = "../prototty" }
wasm-bindgen = "0.2"
