[package]
name = "fib_file_mono"
version = "0.1.0"
authors = ["Stephen Sherratt <sfsherratt@gmail.com>"]

[dependencies]
prototty_monolithic_storage = { path = "../../../monolithic-storage" }
fib = { path = "../fib" }
