[package]
name = "fib_wasm_old"
version = "0.1.0"
authors = ["Stephen Sherratt <sfsherratt@gmail.com>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
prototty_wasm_storage = { path = "../../../wasm-storage" }
fib = { path = "../fib" }
wasm-bindgen = "0.2"
