language: rust
matrix:
  include:
  - os: linux
    rust: stable
  - os: linux
    rust: beta
  - os: linux
    rust: nightly
  - os: osx
    rust: stable
  allow_failures:
  - rust: nightly
dist: trusty
before_script:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install libasound2-dev; fi
  - nvm use v12
  - cargo install wasm-bindgen-cli
  - npm install -g npx
  - rustup target add wasm32-unknown-unknown
script:
- ./test.sh
