[workspace]

members = [
    "prototty",
    "render",
    "decorator",
    "menu",
    "text",
    "grid",
    "glutin",
    "unix",
    "wasm",
    "storage",
    "input",
    "file-storage",
    "event-routine",
    "monolithic-storage",

    "examples/title/prototty",
    "examples/title/glutin",
    "examples/title/unix",
    "examples/title/wasm",

    "examples/fib/fib",
    "examples/fib/file",
    "examples/fib/wasm",

    "examples/tetris/tetris",
    "examples/tetris/prototty",
    "examples/tetris/glutin",
    "examples/tetris/unix",
    "examples/tetris/wasm",

    "examples/optional_features",

    "examples/drag/prototty",
    "examples/drag/unix",
    "examples/drag/glutin",
    "examples/drag/wasm",

    "examples/pager/prototty",
    "examples/pager/unix",
    "examples/pager/glutin",
    "examples/pager/wasm",

    "examples/colour_picker/prototty",
    "examples/colour_picker/glutin",
    "examples/colour_picker/unix",
    "examples/colour_picker/wasm",

    "examples/roguelike/prototty",
    "examples/roguelike/glutin",
    "examples/roguelike/unix",
    "examples/roguelike/wasm",

    "examples/colour_grid/prototty",
    "examples/colour_grid/glutin",
    "examples/colour_grid/unix",
    "examples/colour_grid/wasm",
]
