[workspace]

members = [
    "chargrid",
    "app",
    "render",
    "decorator",
    "menu",
    "text",
    "graphical",
    "graphical-gfx",
    "graphical-common",
    "ansi-terminal",
    "web",
    "input",
    "event-routine",
    "test-grid",

    "examples/tetris/tetris",
    "examples/tetris/app",
    "examples/tetris/graphical",
    "examples/tetris/ansi-terminal",
    "examples/tetris/web",

    "examples/drag/app",
    "examples/drag/ansi-terminal",
    "examples/drag/graphical",
    "examples/drag/web",

    "examples/pager/app",
    "examples/pager/ansi-terminal",
    "examples/pager/graphical",
    "examples/pager/web",

    "examples/colour_picker/app",
    "examples/colour_picker/graphical",
    "examples/colour_picker/ansi-terminal",
    "examples/colour_picker/web",

    "examples/roguelike/ecs",
    "examples/roguelike/procgen",
    "examples/roguelike/vector",
    "examples/roguelike/rational",
    "examples/roguelike/rand-range",
    "examples/roguelike/game",
    "examples/roguelike/app",
    "examples/roguelike/native",
    "examples/roguelike/graphical",
    "examples/roguelike/ansi-terminal",
    "examples/roguelike/web",

    "examples/colour_grid/app",
    "examples/colour_grid/graphical",
    "examples/colour_grid/ansi-terminal",
    "examples/colour_grid/web",

    "examples/soundboard/app",
    "examples/soundboard/graphical",
    "examples/soundboard/ansi-terminal",
    "examples/soundboard/web",
]

[profile.release]
lto = true
