[workspace]

members = [
    "prototty",
    "app",
    "render",
    "decorator",
    "menu",
    "text",
    "graphical",
    "graphical-gfx",
    "graphical-common",
    "ansi-terminal",
    "web",
    "storage",
    "audio",
    "input",
    "file-storage",
    "event-routine",
    "native-audio",
    "test-grid",

    "examples/fib/fib",
    "examples/fib/file",
    "examples/fib/web",

    "examples/tetris/tetris",
    "examples/tetris/prototty",
    "examples/tetris/graphical",
    "examples/tetris/ansi-terminal",
    "examples/tetris/web",

    "examples/drag/prototty",
    "examples/drag/ansi-terminal",
    "examples/drag/graphical",
    "examples/drag/web",

    "examples/pager/prototty",
    "examples/pager/ansi-terminal",
    "examples/pager/graphical",
    "examples/pager/web",

    "examples/colour_picker/prototty",
    "examples/colour_picker/graphical",
    "examples/colour_picker/ansi-terminal",
    "examples/colour_picker/web",

    "examples/roguelike/ecs",
    "examples/roguelike/procgen",
    "examples/roguelike/vector",
    "examples/roguelike/rational",
    "examples/roguelike/rand-range",
    "examples/roguelike/game",
    "examples/roguelike/prototty",
    "examples/roguelike/native",
    "examples/roguelike/graphical",
    "examples/roguelike/ansi-terminal",
    "examples/roguelike/web",

    "examples/colour_grid/prototty",
    "examples/colour_grid/graphical",
    "examples/colour_grid/ansi-terminal",
    "examples/colour_grid/web",

    "examples/soundboard/prototty",
    "examples/soundboard/graphical",
    "examples/soundboard/ansi-terminal",
    "examples/soundboard/web",
]

[profile.release]
lto = true

[patch.crates-io]
wgpu_glyph = { git = "https://github.com/hecrj/wgpu_glyph", rev = "5fc683fabaaacf924abaf5fa0da08ab3b91a03ed" }
