[workspace]

members = [
    "prototty",
    "render",
    "common",
    "grid",
    "glutin",
    "unix",
    "wasm",
    "storage",
    "input",
    "file-storage",
    "monolithic-storage",
    "wasm-input",
    "wasm-render",
    "wasm-storage",

    "examples/title/prototty",
    "examples/title/glutin",
    "examples/title/unix",
    "examples/title/unix_border",
    "examples/title/wasm",

    "examples/fib/fib",
    "examples/fib/file",
    "examples/fib/wasm",

    "examples/tetris/tetris",
    "examples/tetris/prototty",
    "examples/tetris/glutin",
    "examples/tetris/unix",
    "examples/tetris/wasm",

    "examples/serialize",
]
