[workspace]

members = [
    "render",
    "common",
    "grid",
    "glutin",
    "unix",
    "wasm",
    "storage",
    "input",
    "file-storage",
    "mono-storage",
    "wasm-storage",

    "examples/title/prototty",
    "examples/title/glutin",
    "examples/title/unix",
    "examples/title/unix_border",
    "examples/title/wasm",

    "examples/fib/fib",
    "examples/fib/file",
    "examples/fib/web",

    "examples/tetris/tetris",
    "examples/tetris/prototty",
    "examples/tetris/glutin",
    "examples/tetris/unix",
    "examples/tetris/wasm",
]
