[workspace]

members = [
    "prototty",
    "render",
    "decorator",
    "menu",
    "text",
    "graphical",
    "ansi-terminal",
    "web",
    "storage",
    "input",
    "file-storage",
    "event-routine",
    "test-grid",

    "examples/title/prototty",
    "examples/title/graphical",
    "examples/title/ansi-terminal",
    "examples/title/web",

    "examples/fib/fib",
    "examples/fib/file",
    "examples/fib/web",

    "examples/tetris/tetris",
    "examples/tetris/prototty",
    "examples/tetris/graphical",
    "examples/tetris/ansi-terminal",
    "examples/tetris/web",

    "examples/drag/prototty",
    "examples/drag/ansi-terminal",
    "examples/drag/graphical",
    "examples/drag/web",

    "examples/pager/prototty",
    "examples/pager/ansi-terminal",
    "examples/pager/graphical",
    "examples/pager/web",

    "examples/colour_picker/prototty",
    "examples/colour_picker/graphical",
    "examples/colour_picker/ansi-terminal",
    "examples/colour_picker/web",

    "examples/roguelike/ecs",
    "examples/roguelike/vector",
    "examples/roguelike/game",
    "examples/roguelike/prototty",
    "examples/roguelike/native",
    "examples/roguelike/graphical",
    "examples/roguelike/ansi-terminal",
    "examples/roguelike/web",

    "examples/colour_grid/prototty",
    "examples/colour_grid/graphical",
    "examples/colour_grid/ansi-terminal",
    "examples/colour_grid/web",
]

[profile.release]
lto = true
