[package]
name = "title_wasm"
version = "0.1.0"
authors = ["Stephen Sherratt <sfsherratt@gmail.com>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
prototty = { path = "../../../prototty", version = "0.19" }
prototty_wasm = { path = "../../../wasm", version = "0.19" }
prototty_title = { path = "../prototty" }
