[package]
name = "title_wasm"
version = "0.1.0"
authors = ["Stephen Sherratt <sfsherratt@gmail.com>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
prototty_wasm_render = { path = "../../../wasm-render", version = "0.21" }
prototty_title = { path = "../prototty" }
wasm-bindgen = "0.2"
