[package]
name = "roguelike_native"
version = "0.1.0"
authors = ["Stephen Sherratt <stephen@sherra.tt>"]
edition = "2018"

[dependencies]
simon = "0.2"
serde_yaml = "0.8"
roguelike_prototty = { path = "../prototty" }
prototty_file_storage = { path = "../../../file-storage" }
