[package]
name = "rip_graphical"
version = "0.1.0"
authors = ["Stephen Sherratt <stephen@sherra.tt>"]
edition = "2018"

[features]
default = ["prototty_graphical"]
force_vulkan = ["prototty_graphical/force_vulkan"]

[dependencies]
env_logger = "0.7"
prototty_graphical = { path = "../../../graphical", optional = true }
prototty_graphical_gfx = { path = "../../../graphical-gfx", optional = true }
rip_prototty = { path = "../prototty" }
rip_native = { path = "../native" }
