[package]
name = "roguelike_graphical"
version = "0.1.0"
authors = ["Stephen Sherratt <stephen@sherra.tt>"]
edition = "2018"

[dependencies]
env_logger = "0.7"
prototty_graphical = { path = "../../../graphical" }
prototty_native_audio = { path = "../../../native-audio" }
roguelike_prototty = { path = "../prototty" }
roguelike_native = { path = "../native" }
