[package]
name = "tetris_unix"
version = "0.1.0"
authors = ["Stephen Sherratt <sfsherratt@gmail.com>"]

[dependencies]
tetris_prototty = { path = "../prototty" }
prototty = { path = "../../../prototty", version = "0.19" }
prototty_unix = { path = "../../../unix", version = "0.19" }
rand = "0.4"
