[package]
name = "tetris_unix"
version = "0.1.0"
authors = ["Stephen Sherratt <stephen@sherra.tt>"]
edition = "2018"

[dependencies]
tetris_prototty = { path = "../prototty" }
prototty_unix = { path = "../../../unix" }
rand = "0.7"
