[package]
name = "tetris_graphical"
version = "0.1.0"
authors = ["Stephen Sherratt <stephen@sherra.tt>"]
edition = "2018"

[dependencies]
tetris_prototty = { path = "../prototty" }
prototty_graphical = { path = "../../../graphical" }
rand = "0.7"
