[package]
name = "soundboard_graphical"
version = "0.1.0"
authors = ["Stephen Sherratt <stephen@sherra.tt>"]
edition = "2018"

[dependencies]
soundboard_prototty = { path = "../prototty" }
prototty_graphical = { path = "../../../graphical" }
prototty_native_audio = { path = "../../../native-audio" }
