[package]
name = "soundboard_asni_terminal"
version = "0.1.0"
authors = ["Stephen Sherratt <stephen@sherra.tt>"]
edition = "2018"

[dependencies]
chargrid_ansi_terminal = { path = "../../../ansi-terminal" }
soundboard_app = { path = "../app" }
general_audio_native = { version = "0.2", features = ["vorbis"] }
