[package]
name = "soundboard_asni_terminal"
version = "0.1.0"
authors = ["Stephen Sherratt <stephen@sherra.tt>"]
edition = "2018"

[dependencies]
prototty_ansi_terminal = { path = "../../../ansi-terminal" }
prototty_native_audio = { path = "../../../native-audio" }
soundboard_prototty = { path = "../prototty" }
