[package]
name = "pager_graphical"
version = "0.1.0"
authors = ["Stephen Sherratt <stephen@sherra.tt>"]
edition = "2018"

[dependencies]
pager_prototty = { path = "../prototty" }
prototty_graphical_ = { path = "../../../graphical_" }
