[package]
name = "tetris_wasm"
version = "0.1.0"
authors = ["Stephen Sherratt <sfsherratt@gmail.com>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
prototty_wasm = { path = "../../../wasm", version = "0.21" }
tetris_prototty = { path = "../prototty" }
wasm-bindgen = "0.2"
rand = { version = "0.6", features = ["wasm-bindgen"] }
