[package]
name = "drag_unix"
version = "0.1.0"
authors = ["Stephen Sherratt <sfsherratt@gmail.com>"]

[dependencies]
drag_prototty = { path = "../prototty" }
prototty_unix = { path = "../../../unix" }
