[package]
name = "fib_wasm"
version = "0.1.0"
authors = ["Stephen Sherratt <sfsherratt@gmail.com>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
fib = { path = "../fib" }
prototty_wasm = { path = "../../../wasm" }
wasm-bindgen = "0.2"
