[package]
name = "rip_ansi_terminal"
version = "0.1.0"
authors = ["Stephen Sherratt <stephen@sherra.tt>"]
edition = "2018"

[dependencies]
env_logger = "0.7"
rand = "0.7"
chargrid_ansi_terminal = { path = "../../../ansi-terminal" }
rip_native = { path = "../native" }
rip_app = { path = "../app" }
