[package]
name = "roguelike_ansi_terminal"
version = "0.1.0"
authors = ["Stephen Sherratt <stephen@sherra.tt>"]
edition = "2018"

[dependencies]
env_logger = "0.7"
prototty_ansi_terminal = { path = "../../../ansi-terminal" }
prototty_native_audio = { path = "../../../native-audio" }
roguelike_native = { path = "../native" }
roguelike_prototty = { path = "../prototty" }
