[package]
name = "tetris_glutin"
version = "0.1.0"
authors = ["Stephen Sherratt <sfsherratt@gmail.com>"]

[dependencies]
tetris_prototty = { path = "../prototty" }
prototty_glutin = { path = "../../../glutin" }
rand = "0.7"
