[package]
name = "tetris_glutin"
version = "0.1.0"
authors = ["Stephen Sherratt <sfsherratt@gmail.com>"]

[dependencies]
tetris_prototty = { path = "../prototty" }
prototty = { path = "../../../prototty", version = "0.18" }
prototty_glutin = { path = "../../../glutin", version = "0.18" }
rand = "0.4"
