[package]
name = "colour_grid_web"
version = "0.1.0"
authors = ["Stephen Sherratt <stephen@sherra.tt>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
prototty_web = { path = "../../../web" }
colour_grid_prototty = { path = "../prototty" }
wasm-bindgen = "0.2"
