[package]
name = "tetris_wasm2"
version = "0.1.0"
authors = ["Stephen Sherratt <stephen@sherra.tt>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
prototty_wasm2 = { path = "../../../wasm2" }
tetris_prototty = { path = "../prototty" }
wasm-bindgen = "0.2"
rand = { version = "0.7", features = ["wasm-bindgen"] }
rand_isaac = "0.2"
