[package]
name = "tetris_prototty"
version = "0.1.0"
authors = ["Stephen Sherratt <stephen@sherra.tt>"]
edition = "2018"

[dependencies]
tetris = { path = "../tetris" }
prototty = { path = "../../../prototty" }
rand = "0.7"
