[package]
name = "prototty_grid"
description = "Implementation of prototty::ViewGrid for use in renderers."
version = "0.18.0"
authors = ["Stephen Sherratt <sfsherratt@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/stevebob/prototty.git"
repository = "https://github.com/stevebob/prototty.git"
documentation = "https://docs.rs/prototty_grid"

[dependencies]
prototty = { path = "../prototty", version = "0.18" }
grid_2d = "0.7"
