[package]
name = "colour_grid_unix"
version = "0.1.0"
authors = ["Stephen Sherratt <stephen@sherra.tt>"]
edition = "2018"

[dependencies]
prototty_unix = { path = "../../../unix" }
colour_grid_prototty = { path = "../prototty" }
