[package]
name = "prototty_wasm"
description = "Wasm frontend for prototty."
version = "0.23.0"
authors = ["Stephen Sherratt <sfsherratt@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/stevebob/prototty.git"
repository = "https://github.com/stevebob/prototty.git"
documentation = "https://docs.rs/prototty_wasm"

[features]
serialize = ["prototty_wasm_render/serialize", "prototty_wasm_input/serialize"]
storage = ["prototty_wasm_storage"]

[dependencies]
prototty_wasm_render = { path = "../wasm-render", version = "0.23" }
prototty_wasm_input = { path = "../wasm-input", version = "0.23" }
prototty_wasm_storage = { path = "../wasm-storage", version = "0.23", optional = true}
