[package]
name = "prototty_wasm"
description = "Wasm frontend for prototty."
version = "0.27.0"
authors = ["Stephen Sherratt <stephen@sherra.tt>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/stevebob/prototty.git"
repository = "https://github.com/stevebob/prototty.git"
documentation = "https://docs.rs/prototty_wasm"
edition = "2018"

[features]
serialize = ["prototty_render/serialize", "prototty_input/serialize"]

[dependencies]
prototty_input = { path = "../input", version = "0.27" }
prototty_render = { path = "../render", version = "0.27" }
prototty_event_routine = { path = "../event-routine", version = "0.27" }
prototty_storage = { path = "../storage", version = "0.27" }
wasm-bindgen = "0.2"
js-sys = "0.3"
grid_2d = "0.13"
serde_json = "1.0"

[dependencies.web-sys]
version = "0.3"
features = [
  'Document',
  'Window',
  'HtmlElement',
  'Element',
  'EventListener',
  'EventTarget',
  'KeyboardEvent',
  'MouseEvent',
  'WheelEvent',
  'Node',
  'HtmlHeadElement',
  'Performance',
  'CssStyleDeclaration',
  'DomRect',
  'Storage',
]
