[package]
name = "prototty_wasm"
description = "Wasm frontend for prototty."
version = "0.27.0"
authors = ["Stephen Sherratt <sfsherratt@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/stevebob/prototty.git"
repository = "https://github.com/stevebob/prototty.git"
documentation = "https://docs.rs/prototty_wasm"

[features]
serialize = ["prototty_render/serialize", "prototty_input/serialize", "prototty_grid/serialize"]
storage = ["prototty_monolithic_storage"]

[dependencies]
prototty_input = { path = "../input", version = "0.27" }
prototty_render = { path = "../render", version = "0.27" }
prototty_grid = { path = "../grid", version = "0.27" }
prototty_event_routine = { path = "../event-routine", version = "0.27" }
prototty_storage = { path = "../storage", version = "0.27", optional = true }
prototty_monolithic_storage = { path = "../monolithic-storage", version = "0.27", optional = true }
wasm-bindgen = "0.2"
js-sys = "0.3"
grid_2d = "0.12"

[dependencies.web-sys]
version = "0.3"
features = [
  'Document',
  'Window',
  'HtmlElement',
  'Element',
  'EventListener',
  'EventTarget',
  'KeyboardEvent',
  'MouseEvent',
  'WheelEvent',
  'Node',
  'HtmlHeadElement',
  'Performance',
  'CssStyleDeclaration',
  'DomRect',
]
