[package]
name = "unix_title_border"
version = "0.1.0"
authors = ["Stephen Sherratt <sfsherratt@gmail.com>"]

[dependencies]
prototty = { path = "../../../prototty", version = "0.21" }
prototty_common = { path = "../../../common", version = "0.21" }
prototty_unix = { path = "../../../unix", version = "0.21" }
prototty_title = { path = "../prototty" }
