[package]
name = "tetris_web"
version = "0.1.0"
authors = ["Stephen Sherratt <stephen@sherra.tt>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
prototty_web = { path = "../../../web" }
tetris_prototty = { path = "../prototty" }
wasm-bindgen = "0.2"
rand = { version = "0.7", features = ["wasm-bindgen"] }
rand_isaac = "0.2"
