[package]
name = "pager_wasm"
version = "0.1.0"
authors = ["Stephen Sherratt <sfsherratt@gmail.com>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
prototty_wasm = { path = "../../../wasm" }
pager_prototty = { path = "../prototty" }
wasm-bindgen = "0.2"
