[package]
name = "roguelike_unix"
version = "0.1.0"
authors = ["Stephen Sherratt <stephen@sherra.tt>"]
edition = "2018"

[dependencies]
prototty_unix = { path = "../../../unix" }
prototty_file_storage = { path = "../../../file-storage" }
roguelike_prototty = { path = "../prototty" }
