[package]
name = "roguelike_unix"
version = "0.1.0"
authors = ["Stephen Sherratt <stephen@sherra.tt>"]
edition = "2018"

[dependencies]
simon = "0.2"
prototty_unix = { path = "../../../unix" }
roguelike_native = { path = "../native" }
roguelike_prototty = { path = "../prototty" }
