[package]
name = "pager_unix"
version = "0.1.0"
authors = ["Stephen Sherratt <sfsherratt@gmail.com>"]
edition = "2018"

[dependencies]
pager_prototty = { path = "../prototty" }
prototty_unix = { path = "../../../unix" }
