[package]
name = "soundboard_prototty"
version = "0.1.0"
authors = ["Stephen Sherratt <stephen@sherra.tt>"]
edition = "2018"

[dependencies]
prototty = { path = "../../../prototty" }
prototty_audio = { path = "../../../audio" }
