[package]
name = "prototty_wasm2"
description = "Wasm frontend for prototty."
version = "0.27.0"
authors = ["Stephen Sherratt <sfsherratt@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/stevebob/prototty.git"
repository = "https://github.com/stevebob/prototty.git"
documentation = "https://docs.rs/prototty_wasm"

[dependencies]
prototty_input = { path = "../input", version = "0.27" }
prototty_render = { path = "../render", version = "0.27" }
prototty_grid = { path = "../grid", version = "0.27" }
wasm-bindgen = "0.2"
js-sys = "0.3"
grid_2d = "0.12"

[dependencies.web-sys]
version = "0.3"
features = [
  'Document',
  'Window',
  'HtmlElement',
  'Element',
  'EventListener',
  'EventTarget',
  'KeyboardEvent',
  'MouseEvent',
  'WheelEvent',
  'Node',
  'HtmlHeadElement',
]
