[package]
name = "prototty"
description = "Wrapper crate for frontend-independent prototty crates"
version = "0.27.0"
authors = ["Stephen Sherratt <sfsherratt@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/stevebob/prototty.git"
repository = "https://github.com/stevebob/prototty.git"
documentation = "https://docs.rs/prototty"

[features]
serialize = [
    "prototty_render/serialize",
    "prototty_input/serialize",
    "prototty_text/serialize",
    "prototty_decorator/serialize",
    "prototty_menu/serialize",
]


[dependencies]
prototty_render = { path = "../render", version = "0.27" }
prototty_input = { path = "../input", version = "0.27" }
prototty_decorator = { path = "../decorator", version = "0.27" }
prototty_text = { path = "../text", version = "0.27" }
prototty_menu = { path = "../menu", version = "0.27" }
prototty_event_routine = { path = "../event-routine", version = "0.27" }
