[package]
name = "prototty"
description = "Utilities for easily and efficiently rendering to a terminal."
version = "0.20.0"
authors = ["Stephen Sherratt <sfsherratt@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/stevebob/prototty.git"
repository = "https://github.com/stevebob/prototty.git"
documentation = "https://docs.rs/prototty"

[features]
serialize = ["serde_derive", "grid_2d/serialize"]

[dependencies]
serde = "1.0"
serde_derive = { version = "1.0", optional = true }
bincode = "1.0"
grid_2d = "0.12"
