[package]
name = "prototty"
description = "Utilities for easily and efficiently rendering to a terminal."
version = "0.21.0"
authors = ["Stephen Sherratt <sfsherratt@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/stevebob/prototty.git"
repository = "https://github.com/stevebob/prototty.git"
documentation = "https://docs.rs/prototty"

[features]
serialize = ["serde/serde_derive", "coord_2d/serialize"]

[dependencies]
serde = "1.0"
coord_2d = "0.2"
