[package]
name = "prototty"
description = "Wrapper crate for frontend-independent prototty crates"
version = "0.21.0"
authors = ["Stephen Sherratt <sfsherratt@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/stevebob/prototty.git"
repository = "https://github.com/stevebob/prototty.git"
documentation = "https://docs.rs/prototty"

[features]
serialize = ["prototty_render/serialize", "prototty_input/serialize", "prototty_common/serialize"]
storage = ["prototty_storage"]

[dependencies]
prototty_render = { path = "../render", version = "0.21" }
prototty_input = { path = "../input", version = "0.21" }
prototty_storage = { path = "../storage", version = "0.21", optional = true }
prototty_common = { path = "../common", version = "0.21" }
