[package]
name = "colour_picker_graphical"
version = "0.1.0"
authors = ["Stephen Sherratt <stephen@sherra.tt>"]
edition = "2018"

[dependencies]
prototty_graphical = { path = "../../../graphical" }
colour_picker_prototty = { path = "../prototty" }
