[package]
name = "colour_picker_graphical"
version = "0.1.0"
authors = ["Stephen Sherratt <stephen@sherra.tt>"]
edition = "2018"

[dependencies]
chargrid_graphical = { path = "../../../graphical" }
colour_picker_app = { path = "../app" }
