[package]
name = "fib"
version = "0.1.0"
authors = ["Stephen Sherratt <sfsherratt@gmail.com>"]

[dependencies]
prototty_storage = { path = "../../../storage", version = "0.21" }
serde = { version = "1.0", features = ["serde_derive"] }
