[package]
name = "prototty_unix"
description = "Prototty context for unix terminals."
version = "0.23.0"
authors = ["Stephen Sherratt <sfsherratt@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/stevebob/prototty.git"
repository = "https://github.com/stevebob/prototty.git"
documentation = "https://docs.rs/prototty_unix"

[features]
serialize = ["prototty_render/serialize", "prototty_input/serialize", "prototty_grid/serialize", "ansi_colour/serialize"]
storage = ["prototty_file_storage"]

[dependencies]
prototty_render = { path = "../render", version = "0.23" }
prototty_input = { path = "../input", version = "0.23" }
prototty_grid = { path = "../grid", version = "0.23" }
prototty_file_storage = { path = "../file-storage", version = "0.23", optional = true }
libc = "0.2"
term = "0.5"
ansi_colour = { path = "/home/steve/src/ansi-colour" }

[dev-dependencies]
prototty = { path = "../prototty", version = "0.23" }

[[example]]
name = "bold"
