[package]
name = "prototty_unix"
description = "Prototty context for unix terminals."
version = "0.19.0"
authors = ["Stephen Sherratt <sfsherratt@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/stevebob/prototty.git"
repository = "https://github.com/stevebob/prototty.git"
documentation = "https://docs.rs/prototty_unix"

[dependencies]
prototty = { path = "../prototty", version = "0.19" }
prototty_grid = { path = "../grid", version = "0.19" }
grid_2d = "0.7"
libc = "0.2"
term = "0.5"
ansi_colour = "0.4"
itertools = "0.7"
