[package]
name = "prototty_common"
description = "Definition of common ui elements and views for use with prototty."
version = "0.19.1"
authors = ["Stephen Sherratt <sfsherratt@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/stevebob/prototty.git"
repository = "https://github.com/stevebob/prototty.git"
documentation = "https://docs.rs/prototty_common"

[dependencies]
prototty = { path = "../prototty", version = "0.19" }
serde = "1.0"
serde_derive = "1.0"
