[package]
name = "roguelike_wasm"
version = "0.1.0"
authors = ["Stephen Sherratt <stephen@sherra.tt>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
prototty_wasm = { path = "../../../wasm" }
roguelike_prototty = { path = "../prototty" }
wasm-bindgen = "0.2"
