[package]
name = "roguelike_glutin"
version = "0.1.0"
authors = ["Stephen Sherratt <stephen@sherra.tt>"]
edition = "2018"

[dependencies]
prototty_glutin = { path = "../../../glutin" }
roguelike_prototty = { path = "../prototty" }
serde_yaml = "0.8"
