[package]
name = "pager_ansi_terminal"
version = "0.1.0"
authors = ["Stephen Sherratt <stephen@sherra.tt>"]
edition = "2018"

[dependencies]
pager_prototty = { path = "../prototty" }
prototty_ansi_terminal = { path = "../../../ansi-terminal" }
