[package]
name = "prototty_wasm_input"
description = "Input normalization for wasm apps"
version = "0.23.0"
authors = ["Stephen Sherratt <sfsherratt@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/stevebob/prototty.git"
repository = "https://github.com/stevebob/prototty.git"
documentation = "https://docs.rs/prototty_wasm_input"

[features]
serialize = ["prototty_input/serialize"]

[dependencies]
prototty_input = { path = "../input", version = "0.23" }
wasm-bindgen = "0.2"
