[package]
name = "prototty_glutin"
description = "Prototty context for glutin windows."
version = "0.20.1"
authors = ["Stephen Sherratt <sfsherratt@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/stevebob/prototty.git"
repository = "https://github.com/stevebob/prototty.git"
documentation = "https://docs.rs/prototty_glutin"

[dependencies]
prototty = { path = "../prototty", version = "0.20" }
prototty_grid = { path = "../grid", version = "0.20" }
glutin = "0.13"
gfx_window_glutin = "0.21"
gfx_device_gl = "0.15"
gfx = "0.17"
gfx_glyph = "0.9"
itertools = "0.7"
