[package]
name = "unix_title"
version = "0.1.0"
authors = ["Stephen Sherratt <sfsherratt@gmail.com>"]

[dependencies]
prototty_unix = { path = "../../../unix" }
prototty_title = { path = "../prototty" }
