[package]
name = "unix_title"
version = "0.1.0"
authors = ["Stephen Sherratt <stephen@sherra.tt>"]

[dependencies]
prototty_unix = { path = "../../../unix" }
prototty_title = { path = "../prototty" }
