[package]
name = "prototty_text"
description = "Prototty text rendering"
version = "0.24.0"
authors = ["Stephen Sherratt <sfsherratt@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/stevebob/prototty.git"
repository = "https://github.com/stevebob/prototty.git"
documentation = "https://docs.rs/prototty_text"

[features]
serialize = ["serde", "prototty_render/serialize"]

[dependencies]
prototty_render = { path = "../render", version = "0.24" }
serde = { version = "1.0", features = ["serde_derive"], optional = true }
