[package]
name = "game"
version = "0.1.0"
authors = ["Stephen Sherratt <stephen@sherra.tt>"]
edition = "2018"

[dependencies]
grid_2d = { version = "0.13", features = ["serialize"] }
direction = { version = "0.17", features = ["serialize"] }
serde = { version = "1.0", features = ["serde_derive"] }
rand = "0.7"
hashbrown = { version = "0.6", features = ["serde"] }
