[package]
name = "title_graphical"
version = "0.1.0"
authors = ["Stephen Sherratt <stephen@sherra.tt>"]

[dependencies]
prototty_graphical = { path = "../../../graphical" }
prototty_title = { path = "../prototty" }
