[package]
name = "prototty_web"
description = "Web frontend for prototty."
version = "0.29.0"
authors = ["Stephen Sherratt <stephen@sherra.tt>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/stevebob/prototty.git"
repository = "https://github.com/stevebob/prototty.git"
documentation = "https://docs.rs/prototty_web"
edition = "2018"

[features]
serialize = ["prototty_render/serialize", "prototty_input/serialize"]

[dependencies]
prototty_app = { path = "../app", version = "0.29" }
prototty_input = { path = "../input", version = "0.29" }
prototty_render = { path = "../render", version = "0.29" }
wasm-bindgen = "0.2"
js-sys = "0.3"
grid_2d = "0.14"
serde_json = "1.0"
base64 = "0.12"
log = "0.4"

[dependencies.web-sys]
version = "0.3"
features = [
  'Document',
  'Window',
  'HtmlElement',
  'Element',
  'EventListener',
  'EventTarget',
  'KeyboardEvent',
  'MouseEvent',
  'WheelEvent',
  'Node',
  'HtmlHeadElement',
  'HtmlMediaElement',
  'Performance',
  'CssStyleDeclaration',
  'DomRect',
]
